steps:
- name: gcr.io/cloud-builders/docker
  dir: Semana_2/sentiment_analysis
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/$PROJECT_ID/sentimientos-repo/sentimientos",
      "."
    ]

- name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/sentimientos-repo/sentimientos"
    ]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  args:
    [
      "gcloud", "run", "deploy", "sentimientos",
      "--image", "us-central1-docker.pkg.dev/$PROJECT_ID/sentimientos-repo/sentimientos",
      "--region", "us-central1",
      "--platform", "managed",
      "--allow-unauthenticated"
    ]

options:
  logging: CLOUD_LOGGING_ONLY